routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Auth::routes();
////// --------- ADMIN ROUTES ----- ///////
Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('/category', 'CategoryController@index')->name('category.index');
    ///resource routes///
    Route::resource('/category', 'CategoryController');
    Route::resource('/states', 'StateController');
    Route::resource('/city', 'CityController');
    Route::resource('/features', 'FeaturesController');
    Route::resource('/featuresCategory', 'FeatureCategoryController');
    Route::resource('/purpose', 'PurposeController');
    Route::resource('/project', 'ProjectController');
    Route::post('/projectphoto/{id}', 'AdminPhotoController@updateProjectPhoto')->name('projectphotoupdate');
    Route::post('/destroyProjectPhoto/{id}', 'AdminPhotoController@destroyProjectPhoto')->name('destroyProjectPhoto');
    Route::get('/features/restore/{feature}', 'FeaturesController@restore')->name('features.restore');
    Route::get('/ajaxfeatures', 'FeaturesController@featuresList')->name('features.list');
    Route::get('/ajaxfeaturescategory', 'FeatureCategoryController@featuresCategoryList')->name('featuresCategory.list');
    Route::get('/featuresCategory/restore/{feature}', 'FeatureCategoryController@restore')->name('featuresCategory.restore');
    Route::resource('/alisting', 'AdminListingController');
    Route::resource('/aphoto', 'AdminPhotoController');
    Route::get('/adminajaxsubcat','AdminListingController@subCat')->name('adminfiltersubcat');
    Route::get('/adminajaxsubcity','ProjectController@subCity')->name('adminfiltersubcity');
    Route::get('/adminajaxcityproject','AdminListingController@cityProject')->name('adminfiltercityproject');
    Route::get('/adminfeatures-categories', 'AdminListingController@features_category')->name('adminfeatures_category.list');
});
///ADMIN ROUTE ENDS
Route::get('/','HomeController@index')->name('user.index');
Route::get('/properety/{slug}.hmtl','HomeController@single')->name('viewSingleListing');
Route::get('/ajaxfilter','HomeController@filter')->name('filters');
Route::get('/submitProperty','ListingController@create')->name('propertysubmit');
Route::get('/view','HomeController@view')->name('gridview');
Route::get('/view/search','HomeController@search')->name('view.search');
Route::get('/view/search/advanced','HomeController@advancedSearch')->name('advanced.search');
Route::get('/ajaxsubcat','HomeController@subCat')->name('filtersubcat');


//User Account

Route::group(['prefix' => 'users', 'middleware' => ['role:user|agent|agency']], function() {
    Route::get('/', 'UsersAccountController@myProfile')->name('user.profile');
    Route::resource('/listing', 'ListingController');
    Route::resource('/photo', 'PhotoController');
    Route::get('/submitProperty','ListingController@create')->name('propertysubmit');
    Route::get('/ajaxsubcat','ListingController@subCat')->name('filtersubcat');
    Route::get('/ajaxsubcity','ProjectController@subCity')->name('filtersubcity');
    Route::get('/ajaxcityproject','ListingController@cityProject')->name('filtercityproject');
    Route::get('/features-categories', 'ListingController@features_category')->name('features_category.list');
    Route::post('/update/my-profile/{id}', 'UsersAccountController@updateMyProfile')->name('user.updateProfile');
    Route::get('/social-media', 'UsersAccountController@socialMedia')->name('user.smedia');
    Route::post('/update/social-media', 'UsersAccountController@updateSocialMedia')->name('user.updateSmedia');
    Route::get('/properties', 'UsersAccountController@myProperties')->name('user.properties');
    Route::get('/favorited-properties', 'UsersAccountController@favoritedProperties')->name('user.fproperties');
    Route::get('/message', 'UsersAccountController@Message')->name('user.message');
    Route::get('/feedback-and-comments', 'UsersAccountController@feedbackAndComments')->name('user.feedback');
    Route::get('/payments-and-invoice', 'UsersAccountController@paymentsAndInvoice')->name('user.payments');
    Route::get('/change-password', 'UsersAccountController@changePassword')->name('user.changepassword');
    Route::post('/change-password/{id}', 'UsersAccountController@updatePassword')->name('user.updatePassword');
});

app/City.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    public function state(){
        return $this->belongsTo('App\State');
    }
    public function projects(){
        return $this->hasMany('App\State');
    }
    use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
}

app/Http/Controllers/CityController.php
<?php
namespace App\Http\Controllers;
use App\City;
use App\Project;
use Illuminate\Http\Request;
use Auth;
use App\State;
class cityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user=Auth::User();
        $cities=City::with('state')->get();
        return view('admin.city.index',compact('user','cities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user= Auth::User();
        $states = State::all();
        return view('admin.city.create', compact('states','user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'max:64|required|unique:cities,name',
            'state' => 'required',
        ]);
        $city = new City;
        $city->name = $request->name;
        $city->slug;
        $city->state_id = $request->state;
        $city->save();
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function show(City $city)
    {
        $user=Auth::User();
        $cities=Project::with('city.state')->where('city_id',$city->id)->get();
        return view('admin.city.show',compact('cities','user','city','state'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function edit(City $city)
    {
        $user=Auth::User();
        $states=State::all();
        return view('admin.city.edit',compact('user','city','states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, City $city)
    {
        $request->validate([
            'name' => 'max:64|required|unique:cities,name',$city->id,
            'state' => 'required',
        ]);
        $city->name = $request->name;
        $city->slug;
        $city->state_id=$request->state;
        $city->save();
        return redirect(route('city.index'))->with(['update'=>'City successfully updated.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function destroy(City $city)
    {
        $city->delete();
        return redirect(route('city.index'))->with(['deleted'=>'City successfully Deleted.']);
    }

    public function ajaxCities(Request $request){
        $cities = City::where('state_id', $request->id)->get();
        $str = '';
        foreach ($cities as $city) {
            $str.="<option value='$city->id'>$city->name</option>";
        }
        return $str;
    }
}

resources/views/admin/city/create.blade.php
@extends('admin.master')
@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    {{--<section class="content-header">--}}
    {{--<h1>--}}
    {{--Add New Category--}}
    {{--</h1>--}}
    {{--<ol class="breadcrumb">--}}
    {{--<li class="breadcrumb-item"><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>--}}
    {{--<li class="breadcrumb-item"><a href="#">Category</a></li>--}}
    {{--<li class="breadcrumb-item active">New</li>--}}
    {{--</ol>--}}
    {{--</section>--}}

    <!-- Main content -->
        <section class="content">

            <!-- Basic Forms -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Add City</h3>
                </div>
                <!-- /.box-header -->
                <form role="form" method="post" action="{{route('city.store')}}">
                    {{csrf_field()}}
                    <div class="box-body">

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group{{ $errors->has('name') ? 'has-error': ''}}">
                                    <label>City Name</label>
                                    <small class="sidetitle">E.g. Lahore Karachi Islamabad</small>
                                    <input type="text" class="form-control" name="name" placeholder="City Name"
                                           required="required" value="">
                                </div>
                            </div>
                            @if($errors->has('name'))
                                <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                            <div class="col-md-6">
                                <div class="form-group{{ $errors->has('state') ? 'has-error': ''}}">
                                    <label>States</label>
                                    <small class="sidetitle">E.g. Punjab Balouchistan Kashmir</small>
                                    <select class="form-control" id="exampleFormControlSelect1" name="state">
                                        @foreach($states as $state)
                                            <option value="{{$state->id}}">{{$state->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                @if($errors->has('state'))
                                    <span class="help-block">
                            <strong>{{ $errors->first('state') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="col-md-6">
                                <br>
                                <br>
                                <div class="form-group float-right">
                                    <label></label>
                                    <small></small>
                                    <button type="submit" class="btn btn-success">
                                        <i class="fa fa-plus mr-5"></i> Add City
                                    </button>
                                </div>
                            </div>

                        </div>

                    </div>
                </form>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@section('page_level_style')
    <script type="text/javascript">
        $(document).ready(function () {
            // Initialize "states" example
            var $states = $(".js-source-states");
            var statesOptions = $states.html();
            $states.remove();

            $(".js-states").append(statesOptions);
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        function formatState(state) {
            if (!state.id) {
                return state.text;
            }

            var $state = $(
                '<span><i class="fa ' + state.element.dataset.icon.toLowerCase() + '" aria-hidden="true"></i> ' + state.text + '</span>'
            );
            return $state;
        };

        $(".js-example-templating").select2({
            templateResult: formatState
        }).addClass("form-control");
    </script>
@endsection
@stop

resources/views/admin/city/edit.blade.php
@extends('admin.master')
@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    {{--<section class="content-header">--}}
    {{--<h1>--}}
    {{--Add New Category--}}
    {{--</h1>--}}
    {{--<ol class="breadcrumb">--}}
    {{--<li class="breadcrumb-item"><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>--}}
    {{--<li class="breadcrumb-item"><a href="#">Category</a></li>--}}
    {{--<li class="breadcrumb-item active">New</li>--}}
    {{--</ol>--}}
    {{--</section>--}}

    <!-- Main content -->
        <section class="content">

            <!-- Basic Forms -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Add City</h3>
                </div>
                <!-- /.box-header -->
                <form role="form" method="post" action="{{route('city.update',$city->id)}}">
                    {{csrf_field()}}
                    <div class="box-body">

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {{ $errors->has('name') ? 'has-error': ''}}">
                                    <label>City Name</label>
                                    <small class="sidetitle">E.g. Lahore Karachi Islamabad</small>
                                    <input type="text" class="form-control" name="name" placeholder="City Name"
                                           required="required" value="{{old('name',$city->name)}}">
                                </div>
                            </div>
                            @if($errors->has('name'))
                                <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                            <div class="col-md-6">
                                <div class="form-group {{ $errors->has('state') ? 'has-error': ''}}">

                                    <select class="form-control" id="exampleFormControlSelect1" name="state">
                                        <label>State</label>
                                        @foreach($states as $state)
                                            @if($state->id == $city->state_id)
                                                <option value="{{$state->id}}" selected="selected">{{$state->name}} </option>
                                            @else
                                                <option value="{{$state->id}}">{{$state->name}}</option>
                                            @endif

                                        @endforeach
                                    </select>
                                </div>
                                @if($errors->has('state'))
                                    <span class="help-block">
                            <strong>{{ $errors->first('state') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="col-md-6">

                                <div class="form-group right-float">
                                    <button type="submit" class="btn btn-success">
                                        <i class="fa fa-plus mr-5"></i> Add City
                                    </button>
                                </div>
                            </div>

                        </div>

                    </div>
                </form>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@section('page_level_style')
    <script type="text/javascript">
        $(document).ready(function () {
            // Initialize "states" example
            var $states = $(".js-source-states");
            var statesOptions = $states.html();
            $states.remove();

            $(".js-states").append(statesOptions);
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        function formatState(state) {
            if (!state.id) {
                return state.text;
            }

            var $state = $(
                '<span><i class="fa ' + state.element.dataset.icon.toLowerCase() + '" aria-hidden="true"></i> ' + state.text + '</span>'
            );
            return $state;
        };

        $(".js-example-templating").select2({
            templateResult: formatState
        }).addClass("form-control");
    </script>
@endsection
@stop

resources/views/admin/city/show.blade.php
@extends('admin.master')
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <!-- Main content -->
        <section class="content">
            <!-- /.row -->
            <div class="row">
                <div class="col-12">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">State -> {{$city->state->name}} | City -> {{$city->name}}</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body no-padding">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <tr>
                                        <th>Sr No#</th>
                                        <th>Project Title</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>

                                    @foreach($cities as $key=>$cat)
                                        <tr>
                                            <td>{{$key+1}}</td>
                                            <td>{{$cat->title}}</td>
                                            <td><a href="{{ route('project.edit', $cat->id) }}"><button class="btn btn-primary">Edit</button></a></td>
                                            <td><input type="submit" class="btn btn-danger" onclick="frmdlt{{$cat->id}}.submit();" value="Delete">
                                                <form onSubmit="if(!confirm('Is the form filled out correctly?')){return false;}" name="frmdlt{{$cat->id}}" action="{{ route('city.destroy', $cat->id)}}" method="post">
                                                    {!! method_field('delete') !!}
                                                    {{csrf_field()}}

                                                </form></td>
                                        </tr>
                                    @endforeach
                                </table>
                            </div>

                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@endsection