routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Auth::routes();
////// --------- ADMIN ROUTES ----- ///////
Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('/category', 'CategoryController@index')->name('category.index');
    ///resource routes///
    Route::resource('/category', 'CategoryController');
    Route::resource('/states', 'StateController');
    Route::resource('/city', 'CityController');
    Route::resource('/features', 'FeaturesController');
    Route::resource('/featuresCategory', 'FeatureCategoryController');
    Route::resource('/purpose', 'PurposeController');
    Route::resource('/project', 'ProjectController');
    Route::post('/projectphoto/{id}', 'AdminPhotoController@updateProjectPhoto')->name('projectphotoupdate');
    Route::post('/destroyProjectPhoto/{id}', 'AdminPhotoController@destroyProjectPhoto')->name('destroyProjectPhoto');
    Route::get('/features/restore/{feature}', 'FeaturesController@restore')->name('features.restore');
    Route::get('/ajaxfeatures', 'FeaturesController@featuresList')->name('features.list');
    Route::get('/ajaxfeaturescategory', 'FeatureCategoryController@featuresCategoryList')->name('featuresCategory.list');
    Route::get('/featuresCategory/restore/{feature}', 'FeatureCategoryController@restore')->name('featuresCategory.restore');
    Route::resource('/alisting', 'AdminListingController');
    Route::resource('/aphoto', 'AdminPhotoController');
    Route::get('/adminajaxsubcat','AdminListingController@subCat')->name('adminfiltersubcat');
    Route::get('/adminajaxsubcity','ProjectController@subCity')->name('adminfiltersubcity');
    Route::get('/adminajaxcityproject','AdminListingController@cityProject')->name('adminfiltercityproject');
    Route::get('/adminfeatures-categories', 'AdminListingController@features_category')->name('adminfeatures_category.list');
});
///ADMIN ROUTE ENDS
Route::get('/','HomeController@index')->name('user.index');
Route::get('/properety/{slug}.hmtl','HomeController@single')->name('viewSingleListing');
Route::get('/ajaxfilter','HomeController@filter')->name('filters');
Route::get('/submitProperty','ListingController@create')->name('propertysubmit');
Route::get('/view','HomeController@view')->name('gridview');
Route::get('/view/search','HomeController@search')->name('view.search');
Route::get('/view/search/advanced','HomeController@advancedSearch')->name('advanced.search');
Route::get('/ajaxsubcat','HomeController@subCat')->name('filtersubcat');


//User Account

Route::group(['prefix' => 'users', 'middleware' => ['role:user|agent|agency']], function() {
    Route::get('/', 'UsersAccountController@myProfile')->name('user.profile');
    Route::resource('/listing', 'ListingController');
    Route::resource('/photo', 'PhotoController');
    Route::get('/submitProperty','ListingController@create')->name('propertysubmit');
    Route::get('/ajaxsubcat','ListingController@subCat')->name('filtersubcat');
    Route::get('/ajaxsubcity','ProjectController@subCity')->name('filtersubcity');
    Route::get('/ajaxcityproject','ListingController@cityProject')->name('filtercityproject');
    Route::get('/features-categories', 'ListingController@features_category')->name('features_category.list');
    Route::post('/update/my-profile/{id}', 'UsersAccountController@updateMyProfile')->name('user.updateProfile');
    Route::get('/social-media', 'UsersAccountController@socialMedia')->name('user.smedia');
    Route::post('/update/social-media', 'UsersAccountController@updateSocialMedia')->name('user.updateSmedia');
    Route::get('/properties', 'UsersAccountController@myProperties')->name('user.properties');
    Route::get('/favorited-properties', 'UsersAccountController@favoritedProperties')->name('user.fproperties');
    Route::get('/message', 'UsersAccountController@Message')->name('user.message');
    Route::get('/feedback-and-comments', 'UsersAccountController@feedbackAndComments')->name('user.feedback');
    Route::get('/payments-and-invoice', 'UsersAccountController@paymentsAndInvoice')->name('user.payments');
    Route::get('/change-password', 'UsersAccountController@changePassword')->name('user.changepassword');
    Route::post('/change-password/{id}', 'UsersAccountController@updatePassword')->name('user.updatePassword');
});

app/State.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class State extends Model{

    public function cities(){
        return $this->hasMany('App\City');
    }
    use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
}

app/Http/Controllers/StateController.php
<?php

namespace App\Http\Controllers;
use App\City;
use Auth;
use App\State;
use Illuminate\Http\Request;

class stateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user=Auth::User();
        $states=State::all();
        return view('admin.state.index',compact('user','states'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user= Auth::User();
        return view('admin.state.create', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'max:64|required|unique:states,name',
        ]);
        $state = new State;
        $state->name = $request->name;
        $state->slug;
        $state->save();



        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function show(State $state)
    {
        $user=Auth::User();
       $cities = City::where('state_id',$state->id)->simplePaginate('10');

       return view('admin.state.show',compact('cities','user','state'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function edit(State $state)
    {
        $user=Auth::User();

        return view('admin.state.edit',compact('user','state'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, State $state)
    {
        $request->validate([
            'name' => 'max:64|required'
        ]);
        $state->name = $request->name;
        $state->slug;
        $state->save();
        return redirect(route('states.index'))->with(['update'=>'State successfully updated.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(State $state)
    {
        $state->delete();
        return redirect(route('states.index'))->with(['deleted'=>'State successfully updated.']);
    }
}

resources/views/admin/state/create.blade.php
@extends('admin.master')
@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    {{--<section class="content-header">--}}
    {{--<h1>--}}
    {{--Add New Category--}}
    {{--</h1>--}}
    {{--<ol class="breadcrumb">--}}
    {{--<li class="breadcrumb-item"><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>--}}
    {{--<li class="breadcrumb-item"><a href="#">Category</a></li>--}}
    {{--<li class="breadcrumb-item active">New</li>--}}
    {{--</ol>--}}
    {{--</section>--}}

    <!-- Main content -->
        <section class="content">

            <!-- Basic Forms -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Add State</h3>
                </div>
                <!-- /.box-header -->
                <form role="form" method="post" action="{{route('states.store')}}">
                    {{csrf_field()}}
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group {{ $errors->has('name') ? 'has-error': ''}}">
                                    <label>State Name</label>
                                    <small class="sidetitle">E.g. Lahore Karachi Islamabad</small>
                                    <input type="text" class="form-control" name="name" placeholder="State Name" required="required" value="">
                                </div>
                            </div>
                            @if($errors->has('name'))
                                <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                            <div class="col-md-12">

                                <div class="form-group right-float">
                                    <button type="submit" class="btn btn-success">
                                        <i class="fa fa-plus mr-5"></i> Add State
                                    </button>
                                </div>
                            </div>

                        </div>

                    </div>
                </form>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@stop

resources/views/admin/state/edit.blade.php
@extends('admin.master')
@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    {{--<section class="content-header">--}}
    {{--<h1>--}}
    {{--Add New Category--}}
    {{--</h1>--}}
    {{--<ol class="breadcrumb">--}}
    {{--<li class="breadcrumb-item"><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>--}}
    {{--<li class="breadcrumb-item"><a href="#">Category</a></li>--}}
    {{--<li class="breadcrumb-item active">New</li>--}}
    {{--</ol>--}}
    {{--</section>--}}

    <!-- Main content -->
        <section class="content">

            <!-- Basic Forms -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Update State</h3>
                </div>
                <!-- /.box-header -->
                <form role="form" method="post" action="{{route('states.update',$state->id)}}">
                    {{csrf_field()}}
                    @method('PUT')
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group{{ $errors->has('name') ? 'has-error': ''}}">
                                    <label>State Name</label>
                                    <small class="sidetitle">E.g. Lahore Karachi Islamabad</small>
                                    <input type="text" class="form-control" name="name" placeholder="State Name" required="required" value="{{old('name',$state->name)}}">
                                </div>
                            </div>
                            @if($errors->has('name'))
                                <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                            <div class="col-md-12">

                                <div class="form-group right-float">
                                    <button type="submit" class="btn btn-success">
                                        <i class="fa fa-plus mr-5"></i> Update State
                                    </button>
                                </div>
                            </div>

                        </div>

                    </div>
                </form>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@stop

resources/views/admin/state/index.blade.php
@extends('admin.master')
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    {{--<section class="content-header">--}}
    {{--<h1>--}}
    {{--Add New Category--}}
    {{--</h1>--}}
    {{--<ol class="breadcrumb">--}}
    {{--<li class="breadcrumb-item"><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>--}}
    {{--<li class="breadcrumb-item"><a href="#">Category</a></li>--}}
    {{--<li class="breadcrumb-item active">New</li>--}}
    {{--</ol>--}}
    {{--</section>--}}

    <!-- Main content -->
        <section class="content">

            <!-- Basic Forms -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">States</h3>
                </div>
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <tr>
                                        <th>ID</th>
                                        <th>State Name</th>
                                        <th>View Cities</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>

                                    @foreach($states as $key=>$cat)
                                        <tr>
                                            <td>{{$key+1}}</td>
                                            <td>{{$cat->name}}</td>
                                            <td><a href="{{ route('states.show', $cat->slug) }}"><button class="btn btn-primary">View Cities</button></a></td>
                                            <td><a href="{{ route('states.edit', $cat->id) }}"><button class="btn btn-primary">Edit</button></a></td>
                                            <td><input type="submit" class="btn btn-danger" onclick="frmdlt{{$cat->id}}.submit();" value="Delete">
                                                <form onSubmit="if(!confirm('Is the form filled out correctly?')){return false;}" name="frmdlt{{$cat->id}}" action="{{ route('states.destroy', $cat->id)}}" method="post">
                                                    {!! method_field('delete') !!}
                                                    {{csrf_field()}}

                                                </form></td>
                                        </tr>
                                    @endforeach
                                </table>
                            </div>
            </div>
        </section>
                        </div>

@endsection

resources/views/admin/state/show.blade.php
@extends('admin.master')
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <!-- Main content -->
        <section class="content">
            <!-- /.row -->
            <div class="row">
                <div class="col-12">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">State -> {{$cat}}</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body no-padding">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <tr>
                                        <th>Sr No#</th>
                                        <th>City Name</th>
                                        <th>View Projects</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>

                                    @foreach($cities as $key=>$cat)
                                        <tr>
                                            <td>{{$key+1}}</td>
                                            <td>{{$cat->name}}</td>
                                            <td><a href="{{ route('city.show', $cat->slug)}}"><button class="btn btn-primary">View Projects</button></a></td>
                                            <td><a href="{{ route('city.edit', $cat->id)}}"><button class="btn btn-primary">Edit</button></a></td>
                                            <td><input type="submit" class="btn btn-danger" onclick="frmdlt{{$cat->id}}.submit();" value="Delete">
                                                <form onSubmit="if(!confirm('Is the form filled out correctly?')){return false;}" name="frmdlt{{$cat->id}}" action="{{ route('city.destroy', $cat->id)}}" method="post">
                                                    {!! method_field('delete') !!}
                                                    {{csrf_field()}}

                                                </form></td>
                                        </tr>
                                    @endforeach
                                </table>
                            </div>

                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@endsection