routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Auth::routes();
////// --------- ADMIN ROUTES ----- ///////
Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('/category', 'CategoryController@index')->name('category.index');
    ///resource routes///
    Route::resource('/category', 'CategoryController');
    Route::resource('/states', 'StateController');
    Route::resource('/city', 'CityController');
    Route::resource('/features', 'FeaturesController');
    Route::resource('/featuresCategory', 'FeatureCategoryController');
    Route::resource('/purpose', 'PurposeController');
    Route::resource('/project', 'ProjectController');
    Route::post('/projectphoto/{id}', 'AdminPhotoController@updateProjectPhoto')->name('projectphotoupdate');
    Route::post('/destroyProjectPhoto/{id}', 'AdminPhotoController@destroyProjectPhoto')->name('destroyProjectPhoto');
    Route::get('/features/restore/{feature}', 'FeaturesController@restore')->name('features.restore');
    Route::get('/ajaxfeatures', 'FeaturesController@featuresList')->name('features.list');
    Route::get('/ajaxfeaturescategory', 'FeatureCategoryController@featuresCategoryList')->name('featuresCategory.list');
    Route::get('/featuresCategory/restore/{feature}', 'FeatureCategoryController@restore')->name('featuresCategory.restore');
    Route::resource('/alisting', 'AdminListingController');
    Route::resource('/aphoto', 'AdminPhotoController');
    Route::get('/adminajaxsubcat','AdminListingController@subCat')->name('adminfiltersubcat');
    Route::get('/adminajaxsubcity','ProjectController@subCity')->name('adminfiltersubcity');
    Route::get('/adminajaxcityproject','AdminListingController@cityProject')->name('adminfiltercityproject');
    Route::get('/adminfeatures-categories', 'AdminListingController@features_category')->name('adminfeatures_category.list');
});
///ADMIN ROUTE ENDS
Route::get('/','HomeController@index')->name('user.index');
Route::get('/properety/{slug}.hmtl','HomeController@single')->name('viewSingleListing');
Route::get('/ajaxfilter','HomeController@filter')->name('filters');
Route::get('/submitProperty','ListingController@create')->name('propertysubmit');
Route::get('/view','HomeController@view')->name('gridview');
Route::get('/view/search','HomeController@search')->name('view.search');
Route::get('/view/search/advanced','HomeController@advancedSearch')->name('advanced.search');
Route::get('/ajaxsubcat','HomeController@subCat')->name('filtersubcat');


//User Account

Route::group(['prefix' => 'users', 'middleware' => ['role:user|agent|agency']], function() {
    Route::get('/', 'UsersAccountController@myProfile')->name('user.profile');
    Route::resource('/listing', 'ListingController');
    Route::resource('/photo', 'PhotoController');
    Route::get('/submitProperty','ListingController@create')->name('propertysubmit');
    Route::get('/ajaxsubcat','ListingController@subCat')->name('filtersubcat');
    Route::get('/ajaxsubcity','ProjectController@subCity')->name('filtersubcity');
    Route::get('/ajaxcityproject','ListingController@cityProject')->name('filtercityproject');
    Route::get('/features-categories', 'ListingController@features_category')->name('features_category.list');
    Route::post('/update/my-profile/{id}', 'UsersAccountController@updateMyProfile')->name('user.updateProfile');
    Route::get('/social-media', 'UsersAccountController@socialMedia')->name('user.smedia');
    Route::post('/update/social-media', 'UsersAccountController@updateSocialMedia')->name('user.updateSmedia');
    Route::get('/properties', 'UsersAccountController@myProperties')->name('user.properties');
    Route::get('/favorited-properties', 'UsersAccountController@favoritedProperties')->name('user.fproperties');
    Route::get('/message', 'UsersAccountController@Message')->name('user.message');
    Route::get('/feedback-and-comments', 'UsersAccountController@feedbackAndComments')->name('user.feedback');
    Route::get('/payments-and-invoice', 'UsersAccountController@paymentsAndInvoice')->name('user.payments');
    Route::get('/change-password', 'UsersAccountController@changePassword')->name('user.changepassword');
    Route::post('/change-password/{id}', 'UsersAccountController@updatePassword')->name('user.updatePassword');
});

resources/views/admin/featuresCategory/create.blade.php
@extends('admin.master')
@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    {{--<section class="content-header">--}}
    {{--<h1>--}}
    {{--Add New Category--}}
    {{--</h1>--}}
    {{--<ol class="breadcrumb">--}}
    {{--<li class="breadcrumb-item"><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>--}}
    {{--<li class="breadcrumb-item"><a href="#">Category</a></li>--}}
    {{--<li class="breadcrumb-item active">New</li>--}}
    {{--</ol>--}}
    {{--</section>--}}

    <!-- Main content -->
        <section class="content">

            <!-- Basic Forms -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Add Features</h3>
                </div>
          <form role="form" action="{{route('featuresCategory.store')}}" method="post"  enctype="multipart/form-data">
          @csrf
              <div class="box-body">
                  <div class="row">
                      <div class="col-md-6">
                      <div class="form-group {{ $errors->has('name') ? 'has-error': ''}}">
                          <label for="name">Feature:</label>
                          <input type="text" required="required" name="name" value="{{ old('name') }}" class="form-control" id="exampleInputEmail1" placeholder="Enter Name">
                          @if($errors->has('name'))
                              <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                              </span>
                          @endif
                      </div>
                  </div>
                      <div class="col-md-12">
                  <div class="float-right">
                        <button type="submit" class="btn btn-primary" name="frmsubmit">Save</button>
                  </div>
                      </div>
              </div>
          </div>
        </form>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/featuresCategory/edit.blade.php
@extends('admin.master')
@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    {{--<section class="content-header">--}}
    {{--<h1>--}}
    {{--Add New Category--}}
    {{--</h1>--}}
    {{--<ol class="breadcrumb">--}}
    {{--<li class="breadcrumb-item"><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>--}}
    {{--<li class="breadcrumb-item"><a href="#">Category</a></li>--}}
    {{--<li class="breadcrumb-item active">New</li>--}}
    {{--</ol>--}}
    {{--</section>--}}

    <!-- Main content -->
        <section class="content">

            <!-- Basic Forms -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Add Features</h3>
                </div>
                <form role="form" action="{{route('featuresCategory.update',$featuresCategory->id)}}" method="post"
                      enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-6">
                            <div class="form-group {{ $errors->has('name') ? 'has-error': ''}}">
                                <label for="exampleInputEmail1">Name :</label>
                                <input type="text" required="required" name="name" class="form-control"
                                       value="{{old('name', $featuresCategory->name)}}" placeholder="Enter Name">
                                @if($errors->has('name'))
                                    <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                             </span>
                                @endif
                            </div>
                        </div>
                            <div class="col-md-12">
                        <div class="float-right">
                            <button type="submit" class="btn btn-primary" name="frmsubmit">Update</button>
                        </div>
                            </div>
                    </div>
                    </div>
                </form>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/featuresCategory/index.blade.php
@extends('admin.master')
@section('content')

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    {{--<section class="content-header">--}}
    {{--<h1>--}}
    {{--Add New Category--}}
    {{--</h1>--}}
    {{--<ol class="breadcrumb">--}}
    {{--<li class="breadcrumb-item"><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>--}}
    {{--<li class="breadcrumb-item"><a href="#">Category</a></li>--}}
    {{--<li class="breadcrumb-item active">New</li>--}}
    {{--</ol>--}}
    {{--</section>--}}

    <!-- Main content -->
        <section class="content">

            <!-- Basic Forms -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Add Features</h3>
                </div>

        <div class="box-body">
            <table id="feature" class="display" style="width:100%">
              <thead>
                      <tr>
                          <th>Id</th>
                          <th>Category</th>
                          <th>Action</th>
                      </tr>
              </thead> 
              <tbody>
              </tbody>
              
            </table>
        </div>
</div>
        </section>
    </div>

@endsection

@section('page_level_script')
 <script type="text/javascript">
 // $(document).ready(function() {

        $('#feature').DataTable({
            dom: 'lBftip',
            buttons: ['copyHtml5', 'excelHtml5', 'csvHtml5', 'pdfHtml5', 'print'],
            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]],
            processing: true,
            serverSide: true,
            ajax: {
                url: '{{route("featuresCategory.list")}}',
            },
            columns: [
                {data: 'id', name: 'id'},
                {data: 'name', name: 'name'},
                {data: 'action'},
            ],
                success:function (data) {
                    console.log(data);
                }
            });
                        
            $(document).on('click', '.feature_delete', function(){
              var e = $(this);
              var id = e.data('id');
              var url = "{{route('featuresCategory.destroy', ':id')}}";
              $.ajax({
                  type: "POST",
                  url: url.replace(':id', id),
                  data: {
                        _method : 'DELETE',
                        _token : "{{@csrf_token()}}"
                  },
                  success: function(data) {
                        e.console.log('Restore');
                        e.addClass('btn-success feature_restore').removeClass('btn-danger feature_delete');
                  }
            });
                  });
            $(document).on('click', '.feature_restore', function(){
              var e = $(this);
              var id = $(this).data('id');
              var url = "{{route('featuresCategory.restore', ':id')}}";
              $.ajax({
                  type: "GET",
                  url: url.replace(':id', id),
                  success: function(data) {
                        e.html('Delete');
                        e.addClass('btn-danger feature_delete').removeClass('btn-success feature_restore');
                  }
            });
                  });
 // });
  </script>
@endsection

resources/views/admin/featuresCategory/show.blade.php
@extends('admin.master')
@section('content')


@endsection